# The URL the site will be built for
base_url = "/"

compile_sass = true
title = "Issue Blog"
description = "A clean, responsive theme"
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
author = "Vincent"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags", name = "Tags"},
]

even_title = "Even"
